### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'RichTextNodeParser') when used in an Astro project

### ISSUE THREAD

**Issue by rshackleton** [kontent-ai/rich-text-resolver-js#2]
Hey, I'm trying to test this in an Astro project but the package doesn't seem to be compatible.

Using the normal import below throws an error.

```ts
import { RichTextNodeParser } from '@pokornyd/kontent-ai-rich-text-parser';
const parser = new RichTextNodeParser();
const parsed = parser.parse("<h1>Test</h1>");
```

```
Cannot read properties of undefined (reading 'RichTextNodeParser')
```

However, importing from the dist folder works.

```ts
import { RichTextNodeParser } from '@pokornyd/kontent-ai-rich-text-parser/dist/src/parser/node/index';
const parser = new RichTextNodeParser();
const parsed = parser.parse("<h1>Test</h1>");
```

StackBlitz example of the issue here: https://stackblitz.com/edit/withastro-astro-xgknjr?file=src/pages/index.astro

**Comment by pokornyd** [comment]
seems to have been caused by discrepancies between es and commonjs module handling, so I build them both (used to be only cjs originally). also slightly refactored the browserParser class which was causing some trouble as well. 

version 0.0.14 has been released, so far seems to have addressed the original issue but don't hesitate to test it yourself and let me know if you find any further hiccups.

**Comment by rshackleton** [comment]
Looks like 0.0.14 does fix the issue, although there are some issues being flagged by publint that might be worth resolving too.

https://publint.dev/@pokornyd/kontent-ai-rich-text-parser@0.0.14

**Comment by Simply007** [comment]
Moved to https://publint.dev/@kontent-ai/rich-text-resolver@0.0.2 - still the module issue is pending
