### ISSUE TITLE
Extend example with more descriptive TS type

### ISSUE THREAD

**Issue by Simply007** [kontent-ai/rich-text-resolver-js#31]
### Motivation

If is possible to use `Partial` for resolution logic and specify what properties the should have provide.

### Proposed solution

Add this to the readme i.e. for image component and table

```ts
const getPortableTextComponents = (element: Elements.RichTextElement): Partial<TPortableTextReactComponents<'image' | 'component' | 'table'>> => ({
```

### Additional context

Usage could be seen in Kontent.ai's storybook RT resolution.

**Comment by pokornyd** [comment]
the usage revolves around types from the @portabletext/types package and `PortableTextReactComponents` (used in the react resolution example) does not have a type argument. I understand a user might want to limit available override options to a subset of blocks but then again, they can do that simply by specifying the blocks they want to override, discarding the rest. adding it as a type parameter seems like a redundant step but if they really wish to implement some limitations, they can achieve it by abstracting the logic and constructing a dumbed down type with `Omit`. still, this seems like a too specific use-case to be included in the readme, wouldn't you agree?

I definitely may have missed some point, so feel free to elaborate further, otherwise I'm willing to close this.
